spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Ajay@1610
    url: jdbc:mysql://localhost:3306/project
    username: root
  application:
    name: Data-Collection
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc :
  swagger-ui:
    path: swagger-ui.html
server:
  port: 9091
